USE DATABASE COVID_ANALYSIS_DB;
USE SCHEMA RAW_DATA;

-- Confirmed Cases Table
CREATE OR REPLACE TABLE CONVENIENT_GLOBAL_CONFIRMED_CASES (
COUNTRY STRING,
DATE DATE,
CONFIRMED_CASES NUMBER
);

-- Country Vaccinations Table
CREATE OR REPLACE TABLE COUNTRY_VACCINATIONS (
COUNTRY STRING,
DATE DATE,
TOTAL_VACCINATIONS NUMBER,
PEOPLE_VACCINATED NUMBER,
PEOPLE_FULLY_VACCINATED NUMBER,
DAILY_VACCINATIONS NUMBER
);

-- Population Table
CREATE OR REPLACE TABLE POPULATION_BY_COUNTRY_2020 (
COUNTRY_OR_DEPENDENCY STRING,
POPULATION_2020 NUMBER
);