USE DATABASE COVID_ANALYSIS_DB;
USE SCHEMA RAW_DATA;

-- Load Confirmed Cases
COPY INTO CONVENIENT_GLOBAL_CONFIRMED_CASES
FROM @COVID_STAGE/CONVENIENT_GLOBAL_CONFIRMED_CASES_FINAL.csv
FILE_FORMAT = CSV_FORMAT;

-- Load Vaccination Data
COPY INTO COUNTRY_VACCINATIONS
FROM @COVID_STAGE/COUNTRY_VACCINATIONS_FINAL.csv
FILE_FORMAT = CSV_FORMAT;

-- Load Population Data
COPY INTO POPULATION_BY_COUNTRY_2020
FROM (
  SELECT $1, $2
  FROM @COVID_STAGE/POPULATION_BY_COUNTRY_2020_FINAL.csv
)
FILE_FORMAT = CSV_FORMAT;