USE DATABASE COVID_ANALYSIS_DB;
USE SCHEMA RAW_DATA;

-- Remove Null Records

DELETE FROM CONVENIENT_GLOBAL_CONFIRMED_CASES
WHERE COUNTRY IS NULL OR DATE IS NULL;

DELETE FROM COUNTRY_VACCINATIONS
WHERE COUNTRY IS NULL OR DATE IS NULL;

DELETE FROM POPULATION_BY_COUNTRY_2020
WHERE COUNTRY_OR_DEPENDENCY IS NULL;