USE DATABASE COVID_ANALYSIS_DB;
USE SCHEMA ANALYTICS;

-- Create Final Analysis View

CREATE OR REPLACE VIEW COVID_ANALYSIS_VIEW AS
SELECT 
    c.COUNTRY,
    c.DATE,
    c.CONFIRMED_CASES,
    v.TOTAL_VACCINATIONS,
    v.PEOPLE_VACCINATED,
    v.PEOPLE_FULLY_VACCINATED,
    v.DAILY_VACCINATIONS,
    p.POPULATION_2020,
    
    (c.CONFIRMED_CASES / p.POPULATION_2020) * 100 AS CASES_PERCENTAGE,
    (v.PEOPLE_VACCINATED / p.POPULATION_2020) * 100 AS VACCINATION_PERCENTAGE

FROM RAW_DATA.CONVENIENT_GLOBAL_CONFIRMED_CASES c
LEFT JOIN RAW_DATA.COUNTRY_VACCINATIONS v
    ON c.COUNTRY = v.COUNTRY
    AND c.DATE = v.DATE
LEFT JOIN RAW_DATA.POPULATION_BY_COUNTRY_2020 p
    ON c.COUNTRY = p.COUNTRY_OR_DEPENDENCY
WHERE YEAR(c.DATE) = 2021;