-- Correlation Between Cases and Vaccination (Australia Example)

SELECT 
    COUNTRY,
    DATE,
    CONFIRMED_CASES,
    PEOPLE_VACCINATED,
    VACCINATION_PERCENTAGE
FROM ANALYTICS.COVID_ANALYSIS_VIEW
WHERE COUNTRY = 'AUSTRALIA'
ORDER BY DATE;

-- Top 10 Countries by Vaccination %

SELECT 
    COUNTRY,
    MAX(VACCINATION_PERCENTAGE) AS MAX_VACCINATION_PERCENT
FROM ANALYTICS.COVID_ANALYSIS_VIEW
GROUP BY COUNTRY
ORDER BY MAX_VACCINATION_PERCENT DESC
LIMIT 10;

-- Top 10 Countries by Cases %

SELECT 
    COUNTRY,
    MAX(CASES_PERCENTAGE) AS MAX_CASES_PERCENT
FROM ANALYTICS.COVID_ANALYSIS_VIEW
GROUP BY COUNTRY
ORDER BY MAX_CASES_PERCENT DESC
LIMIT 10;